# 项目配置信息
app:
  env: dev
  debug: false
  app_id: wx27c89241d93f10d3
  app_secret: 5f8833e38748aa345e3b8e919241d2ce

jwt:
  secret: z9tld5hG07Mgz1wm995xeH4yKYOprz9NALqQj2bBDUs
  expires_time: 3600
  buffer_time: 3600

server:
  http: 8081
  websocket: 8083
  rpc: 8889


# 日志配置
log:
  # 日志文件路径 *请使用绝对路径*
  path: "/path/to/.../runtime"

# Redis 相关配置
redis:
  host: 127.0.0.1:6379
  auth: xxx
  database: 0

# Mysql 数据库配置
mysql:
  host: rm-2vc07j70dkt06423xuo.mysql.cn-chengdu.rds.aliyuncs.com
  port: 3306
  charset: utf8mb4
  username: root
  password: 45_HqZDac5mnY*K
  database: hyper
  collation: utf8mb4_general_ci

# 跨域配置
cors:
  origin: "*"
  headers: "Content-Type,Cache-Control,User-Agent,Keep-Alive,DNT,AccessToken,Authorization"
  methods: "OPTIONS,GET,POST,PUT,DELETE"
  credentials: false
  max_age: 600